AWSTemplateFormatVersion: 2010-09-09
Description: Lambda@Edge function for Origin Request modification

Parameters:
    ResourcePrefix:
        Type: String
        Description: Prefix to use for resource names

Resources:
  EdgeLambdaRole:
      Type: AWS::IAM::Role
      Properties:
          RoleName: !Sub "${ResourcePrefix}-edge-lambda-role"
          AssumeRolePolicyDocument:
              Version: '2012-10-17'
              Statement:
                  - Effect: Allow
                    Principal:
                        Service:
                            - lambda.amazonaws.com
                            - edgelambda.amazonaws.com
                    Action: sts:AssumeRole
          ManagedPolicyArns:
              - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          Path: "/"

  EdgeLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
          FunctionName: !Sub "${ResourcePrefix}-edge-lambda"
          Code:
              ZipFile: |
                  def lambda_handler(event, context):
                      request = event['Records'][0]['cf']['request']
                      uri = request['uri']
                      
                      headers = request.get('headers', {})
                      
                      referer = headers.get('referer', [{'value': ''}])[0].get('value', '')
                      print(f"Referer: {referer}")
                      
                      try:
                          if referer:
                              folder = referer.split('://')[-1].split('/')[1]
                              uri = uri.lstrip('/')
                              request['uri'] = f"/{folder}/{uri}"
                              print(f"Modified URI: {request['uri']}")
                          else:
                              print("No referer found")
                      except Exception as e:
                          print(f"Error: {e}")
                          
                      return request

          Handler: index.lambda_handler
          Role: !GetAtt EdgeLambdaRole.Arn
          Runtime: python3.9
          Timeout: 5
          MemorySize: 128

  EdgeLambdaVersion:
      Type: AWS::Lambda::Version
      Properties:
          FunctionName: !Ref EdgeLambdaFunction
          Description: v1

Outputs:
  LambdaVersionArn:
      Description: Lambda function version ARN
      Value: !Ref EdgeLambdaVersion
      Export:
          Name: !Sub "${ResourcePrefix}-edge-lambda-version"